### ISSUE TITLE
引入 ant-design-vue 后启动速度很慢

### ISSUE THREAD

**Issue by izhaoqing** [antfu/vitesse-lite#20]
首先我克隆项目到本地

```
npx degit antfu/vitesse-lite my-vitesse-app
cd my-vitesse-app
pnpm i
```

安装 and-design-vue 后修改 vite.config.ts

```ts
import { AntDesignVueResolver } from 'unplugin-vue-components/resolvers'

export default defineConfig({// https://github.com/antfu/vite-plugin-components
    Components({
      dts: true,
      resolvers: [
        AntDesignVueResolver(),
      ],
    }),
})
```

在 pages/index.vue 里使用组件

```html
<template>
<a-range-picker />
</template>
```

demo 地址 [https://github.com/izhaoqing/my-vitesse-app](https://github.com/izhaoqing/my-vitesse-app)

从启动项目到能看到页面需要两分钟，我在 pages/index.vue 里再使用一个 `<a-button>123</a-button>` 组件，又需要一分钟才能看到效果。

**Comment by antfu** [comment]
This is out-of-scope of this template, please report upstream instead.
