### ISSUE TITLE
isDark ref value

### ISSUE THREAD

**Issue by kleinpetr** [antfu/vitesse-lite#21]
The reactivity in the Footer component doesn't work. It is necessary to use `.value` explicitly

original:
```html
<div v-if="isDark" i-carbon-moon />
<div v-else i-carbon-sun />
```

fix:
```html
<div v-if="isDark".value i-carbon-moon />
<div v-else i-carbon-sun />
```

**Comment by antfu** [comment]
Fixed in 0f87c0e2370c96dda520b648edcf75b5ebc7b366

**Comment by kleinpetr** [comment]
thanks, btw why there is needed to use `.value` explicitly?

**Comment by antfu** [comment]
See https://github.com/unjs/unimport/pull/15
