### ISSUE TITLE
Duplicated imports ""

### ISSUE THREAD

**Issue by laddish** [antfu/vitesse-lite#26]
### Describe the bug

# bug 简要说明：
命令行提示：
```
Duplicated imports "", the one from "D:/antfu/vitesse-lite-test/src/composables/divide.ts" has been ignored
Duplicated imports "", the one from "D:/antfu/vitesse-lite-test/src/composables/sum.ts" has been ignored
```
查看生成的 `auto-imports.d.ts`中，`declare global` 中重复声明了空字符串。
```
  const : typeof import('./src/composables/minus')['']
```

# 最小重现仓库地址：
https://github.com/laddish/vitesse-lite-test/tree/test-duplicated-imports-of-empty-string

# 最小重现步骤：
1. clone `vitesse-lite` 这个项目；
2. `ni` 安装依赖；
3. 在 src/composables 下创建 sum.ts
内容为
```
const numA = 1
const numB = 2
export {
  numA,
  numB,
}
```
4. 在 src/composables 下创建 minus.ts
内容为
```
const numC = 1
const numD = 2
export {
  numC,
  numD,
}
```
5. 在 src/composables 下创建 divide.ts
内容为
```
const numE = 1
const numF = 2
export {
  numE,
  numF,
}
```
6. `nr dev` 启动项目
7. 命令行 提示
```
  ➜  Local:   http://127.0.0.1:3333/
  ➜  Network: use --host to expose
Duplicated imports "", the one from "D:/antfu/vitesse-lite-test/src/composables/divide.ts" has been ignored
Duplicated imports "", the one from "D:/antfu/vitesse-lite-test/src/composables/sum.ts" has been ignored
```
8. 查看 `auto-imports.d.ts`，注意到自动生成了这样一行代码
```
  const : typeof import('./src/composables/minus')['']
```

# 其他说明
## 对比 unplugin-auto-import
这个 bug 最开始我怀疑是 `unplugin-auto-import`(https://github.com/antfu/unplugin-auto-import) 的，
因为 `auto-imports.d.ts` 文件是 `unplugin-auto-import` 生成的；
但是我把 `unplugin-auto-import` clone 到本地，
按照以上步骤 在 `unplugin-auto-import`的  playground 文件夹中尝试复现，
生成的 `auto-imports.d.ts` 是正常的，没有空字符串，没有出现上述bug；

## 对比 vitesse 
于是我尝试在 vitesse 复现；
在 vitesse 中，重复上面的步骤，命令行并没有报这样的提示，查看 `auto-imports.d.ts`也是正常的。

vitesse 最小重现地址（没有这个bug，没有出现这个提示，只是对比）
https://github.com/laddish/vitesse-test/tree/test-duplicated-imports-of-empty-string

# 尝试避免这个 bug
按照复现步骤在导出的时候不要换行，
这样就不会在 vitesse-lite 中触发这个bug。
所以这个 bug 可能是换行引起的？
sum.ts
```
const numA = 1
const numB = 2
export { numA, numB }
```
minus.ts
```
const numC = 1
const numD = 2
export { numC, numD }
```

divide.ts
```
const numE = 1
const numF = 2
export { numE, numF }
```
针对这种写法的仓库地址
https://github.com/laddish/vitesse-lite-test/tree/test-no-duplicated-imports-of-empty-string

### Reproduction

https://github.com/laddish/vitesse-lite-test/tree/test-duplicated-imports-of-empty-string

### System Info

```Shell
windows
chrome
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It was fixed in `unplugin-auto-import@0.10.1`, can you bump the version and try again?

**Comment by laddish** [comment]
> It was fixed in `unplugin-auto-import@0.10.1`, can you bump the version and try again?

I just tried, It Works like a charm, thank you! :)
