### ISSUE TITLE
Multiple route levels

### ISSUE THREAD

**Issue by eddysalzmann** [antfu/vitesse-lite#29]
### Clear and concise description of the problem

I tried to copied the logic over to a second route level by adding a, let's say "[place].vue" file inside a "[name]" folder based on the previous [name].vue file, but can't make it work. How would be an approach look like for multiple levels of dynamic routes?

### Suggested solution

Add multiple dynamic route levels to doc

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cirolosapio** [comment]
you mean [this](https://stackblitz.com/edit/github-7zkeci?file=src/pages/hi/[name]/[place].vue)?

**Comment by antfu** [comment]
Report to https://github.com/hannoeru/vite-plugin-pages

**Comment by eddysalzmann** [comment]
Yer like this BUT where we keep them both separated, so first we ask for the name, on the name page we ask for the place. I don't seem to get the props handed over to the deeper level, like [this](https://stackblitz.com/edit/github-7zkeci-3im96f?file=src/pages/hi/[name].vue)
