### ISSUE TITLE
web component from this template

### ISSUE THREAD

**Issue by mdbetancourt** [antfu/vitesse-lite#31]
### Clear and concise description of the problem

how to create web components (to use with other frameworks) with the configuration provided with this template, i almost make it works but unocss is not generating any style (i'm using attributify mode)

### Suggested solution

maybe an example or another template?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Out-of-scope. Feel free to maintain your own variation.
