### ISSUE TITLE
 ERR_PNPM_BAD_PM_VERSION  on pnpm i

### ISSUE THREAD

**Issue by Musickiller** [antfu/vitesse-lite#49]
### Describe the bug

When I run pnpm i, I get following error message: 

ERR_PNPM_BAD_PM_VERSION  This project is configured to use v9.0.2 of pnpm. Your current pnpm is v9.1.1

That doesn't happen for vitesse. Should I drop the strict version check, or should you update something in the repo?

### Reproduction

pnpm i

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.85 GB / 31.88 GB
  Binaries:
    Node: 22.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.1 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.1.7 - C:\ProgramData\chocolatey\bin\bun.EXE
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
You should enable core pack: https://github.com/antfu/contribute#corepack
